language: php
php:
  - '7.2'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit --configuration phpunit.xml --coverage-text
notifications:
  email:
    on_success: never
    on_failure: always
env:
  - TESTFOLDER = tests/controllers
  - TESTFOLDER = tests/validation
