language: php
php:
  - '7.2'
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: phpunit --configuration phpunit.xml --coverage-text
notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    rooms:
      - wilokegroup:1bS7SWI4jj1Jy9Krr3RSHIwd#general
      - wilokegroup:1bS7SWI4jj1Jy9Krr3RSHIwd#random
      - wilokegroup:1bS7SWI4jj1Jy9Krr3RSHIwd#hsblog
    on_success: always
    on_failure: always
env:
  - TESTFOLDER = tests/controllers
  - TESTFOLDER = tests/validation
